### ISSUE TITLE
options for ArchGDAL driver when saving Geotiff ✅ 

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/SimpleSDMLayers.jl#150]
### Description of the to-do item

support for different drivers when writing geotiff

### More information about the item

The current `geotiff` function for writing files uses the GTiff driver in ArchGDAL by default.

https://github.com/PoisotLab/SimpleSDMLayers.jl/blob/dcc49145c2c844bfe63fff99b96cf86720076512/src/datasets/geotiff.jl#L191

It would be nice to have this either be a keyword argument or something to enable selection of different drivers, e.g. I need to use the "COG" driver to write a cloud-optimized geotiff

**Comment by tpoisot** [comment]
Yeah that's a good idea, and probably something that we need to abstract away from this package (I'm in the process of re-designing the data download/load/write layer in another repo). Meanwhile, a PR with a keyword argument is probably the most effort-effective solution?
